### ISSUE TITLE
Tests for different array types

### ISSUE THREAD

**Issue by sidg54** [kurtmdean/A1-part2#11]
We have added the below tests to our test-array.cpp file to test int, bool, and float arrays and were wondering if you could add them into the tests?

void test_int_arrays() {
    init();
    Integer * i = new Integer(1);
    arr->add(i);
    t_true(arr->size() == 1);
    t_true(arr->get_type() == 3);
}

void test_bool_arrays() {
    init();
    Boolean * b = new Boolean(true);
    arr->add(b);
    t_true(arr->size() == 1);
    t_true(arr->get_type() == 4);
}

void test_float_arrays() {
    init();
    Float * b = new Float(1.2);
    arr->add(b);
    t_true(arr->size() == 1);
    t_true(arr->get_type() == 2);
}

**Comment by noelprince** [comment]
Yes thank you for writing those; we will add them ASAP.

**Comment by noelprince** [comment]
Added. Boolean should be Bool to match array.h.
