### ISSUE TITLE
Existing implementation in string.h

### ISSUE THREAD

**Issue by abhishekir** [kurtmdean/A1-part2#2]
Hello, I just wanted to let you know that as per the FAQ at https://piazza.com/class/k51bluky59n2jr?cid=317 I don't think you are supposed to have an implementation for string.h in this repo. The precise restrictions are in the second point in the linked Piazza post.

**Comment by noelprince** [comment]
We are going to conform to the standardized string.h and object.h in https://piazza.com/class/k51bluky59n2jr?cid=330 if that works for you. It should make everything a bit more simple.

**Comment by noelprince** [comment]
We removed the files as to https://piazza.com/class/k51bluky59n2jr?cid=356

**Comment by noelprince** [comment]
We removed the implementations but kept the interface per the same piazza post.

**Comment by sidg54** [comment]
Thank you for noting this
