### ISSUE TITLE
Undefined function from unincluded helper.h

### ISSUE THREAD

**Issue by sidg54** [kurtmdean/A1-part2#4]
In test-array.cpp we found a Cout object (on line 13), and we believe this is from a helper.h file which was not included. Can you tell us the contents of that function or add that object to the test-array.cpp file please? Otherwise it is impossible to compile and run tests.

**Comment by sidg54** [comment]
Nevermind, just saw the updated repo containing helper.h. My apologies for any inconvenience.

**Comment by noelprince** [comment]
Should work now if you pull; feel free to ask if you have any other input or questions
