### ISSUE TITLE
test-array.cpp does not contain a main function or any way to actually run tests

### ISSUE THREAD

**Issue by erikuhlmann** [kurtmdean/A1-part2#6]
Please find some way to have test-array.cpp actually run the tests, including the ones that should abort
 (ie adding at a bad index). You could use Google Test for this (see piazza)

**Comment by noelprince** [comment]
For now, I created a main to run all of the tests. I will talk to my partner about expanding

**Comment by erikuhlmann** [comment]
Yeah currently the tests terminate on the bad index tests, since our implementation terminates when add is called with a bad index. We would appreciate a test system where the tests can continue after expected aborts.

**Comment by kurtmdean** [comment]
I have separated tests that expect aborts and commented them out. They still serve as spec for your implementation, but should not interrupt the "positive" tests anymore. No Google Test for now.
