### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by sidg54** [kurtmdean/A1-part2#9]
We are receiving the following error when trying to compile with `g++ test-array.cpp`. 

Undefined symbols for architecture x86_64:
  "Sys::pln(char const*)", referenced from:
      OK(char const*) in test-array-66e091.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation).

We believe the issue is because the methods in helper.h are not defined within the Sys class but we could be wrong. Any suggestions on how we should proceed?

**Comment by noelprince** [comment]
they definitely should be defined within the sys class. It will be hard to debug on my side so for now I will change the interface to use printf instead; tell me if this helps

**Comment by noelprince** [comment]
If that helps, close the issue after; otherwise, comment again and explain what is going on

**Comment by sidg54** [comment]
Thank you for this, this stopped the compile errors. We'll look into it further and let you know if we find anything but closing this issue for now. Thanks for your help!
